"""Identify-layer attack family catalog.

Simulatable families have overlay templates and can be generated as rows.
Identified-only families are discovered from threat intel but not yet simulated.
"""

from __future__ import annotations

from typing import Any

TAXONOMY = [
    "ai_social_engineering",
    "ai_identity_fraud",
    "account_takeover",
    "payment_initiation",
    "authorization_fraud",
    "transaction_execution",
    "merchant_interaction",
    "digital_wallet",
    "card_payment",
    "upi_fraud",
    "qr_payment",
    "payment_link",
    "refund_fraud",
    "chargeback_fraud",
    "agentic_payment",
    "coordinated_networks",
    "adaptive_fraud",
]

DIVERSITY_TARGET = 30

# BUILD REQUEST five vectors → catalog families. Adversarial generate uses
# a simulatable overlay plus the evolutionary perturber, not DQN.
CORE_ATTACK_VECTORS: list[dict[str, str]] = [
    {
        "id": "AI_Phishing_ATO",
        "family": "phishing_ato",
        "name": "AI Phishing → Account Takeover",
    },
    {
        "id": "Synthetic_Identity",
        "family": "synthetic_identity",
        "name": "Synthetic Identity → KYC Bypass",
    },
    {
        "id": "Voice_Cloning_UPI",
        "family": "deepfake_upi",
        "name": "Voice Cloning → APP / UPI",
    },
    {
        "id": "AI_Agent_Intent_Mismatch",
        "family": "malicious_agent",
        "name": "AI Agent → Intent Mismatch",
    },
    {
        "id": "Adversarial_Transaction",
        "family": "adversarial_row",
        "generate_as": "phishing_ato",
        "name": "Adversarial Transactions → Evasion",
    },
]
CORE_FAMILY_IDS = [row["family"] for row in CORE_ATTACK_VECTORS]
VECTOR_TO_FAMILY = {row["id"]: row.get("generate_as") or row["family"] for row in CORE_ATTACK_VECTORS}

# Identity + authentication pack. Payment-side overlays only — no GAN faces,
# forged document images, phishing copy, or cloned audio.
IDENTITY_AUTH_FAMILY_IDS = [
    "synthetic_identity",
    "deepfake_kyc",
    "document_forgery",
    "face_swap",
    "voice_clone_auth",
    "phishing_ato",
    "voice_impersonation",
    "deepfake_video",
    "multilingual_scam",
]


def _entry(
    *,
    name: str,
    category: str,
    evidence: str,
    feasibility: str,
    tier: int,
    attack_surface: str,
    ai_component: str,
    payment_impact: str,
    detectable_signals: list[str],
    signal_layers: dict[str, list[str]],
    owasp: list[str],
    simulatable: bool,
    keywords: list[str],
) -> dict[str, Any]:
    return {
        "name": name,
        "category": category,
        "evidence": evidence,
        "feasibility": feasibility,
        "tier": tier,
        "attack_surface": attack_surface,
        "ai_component": ai_component,
        "payment_impact": payment_impact,
        "detectable_signals": detectable_signals,
        "signal_layers": signal_layers,
        "owasp": owasp,
        "simulatable": simulatable,
        "keywords": keywords,
    }


# Keep aligned with features.FAMILY_TEMPLATES for simulatable ids.
ATTACK_CATALOG: dict[str, dict[str, Any]] = {
    "phishing_ato": _entry(
        name="AI Phishing → Account Takeover",
        category="account_takeover",
        evidence="ESTABLISHED",
        feasibility="HIGH",
        tier=1,
        attack_surface="Email or SMS lure + new-device login + card-not-present purchase",
        ai_component="LLM-personalized lure that drives a session from a new device",
        payment_impact="Unauthorized high-value purchase shortly after credential use",
        detectable_signals=["device_new", "velocity_1h", "location_mismatch"],
        signal_layers={"rules": ["device_new", "velocity_1h"], "ml": ["Amount"], "graph": [], "intent": []},
        owasp=["LLM01"],
        simulatable=True,
        keywords=["phish", "phishing", "email", "ato", "takeover", "credential", "cnp"],
    ),
    "deepfake_upi": _entry(
        name="Deepfake Voice → UPI Collect Request",
        category="upi_fraud",
        evidence="ESTABLISHED",
        feasibility="HIGH",
        tier=1,
        attack_surface="Voice call + collect-style debit + mule beneficiary",
        ai_component="Voice clone impersonating a family member to approve a collect request",
        payment_impact="Victim-authorized debit to a mule account",
        detectable_signals=["beneficiary_name_match", "mule_account_risk", "Amount"],
        signal_layers={
            "rules": ["beneficiary_name_match"],
            "ml": ["Amount"],
            "graph": ["mule_account_risk"],
            "intent": [],
        },
        owasp=["LLM06", "LLM09"],
        simulatable=True,
        keywords=["deepfake", "voice", "clone", "upi", "collect", "family", "app scam"],
    ),
    "malicious_agent": _entry(
        name="Malicious AI Agent → Constraint Violation",
        category="agentic_payment",
        evidence="EMERGING",
        feasibility="HIGH",
        tier=1,
        attack_surface="Delegated agent credentials + checkout API",
        ai_component="Compromised agent ignores spend limit and merchant constraints",
        payment_impact="Payment above the delegated limit",
        detectable_signals=["constraint_violation", "amount_vs_limit_ratio", "velocity_1h"],
        signal_layers={
            "rules": ["velocity_1h"],
            "ml": ["Amount"],
            "graph": [],
            "intent": ["constraint_violation", "amount_vs_limit_ratio"],
        },
        owasp=["LLM06"],
        simulatable=True,
        keywords=["agent", "agentic", "delegat", "constraint", "intent", "agent pay"],
    ),
    "synthetic_identity": _entry(
        name="Synthetic Identity → New Account Fraud",
        category="ai_identity_fraud",
        evidence="ESTABLISHED",
        feasibility="HIGH",
        tier=1,
        attack_surface="Onboarding + first-week CNP spend",
        ai_component="Generative identity packet that passes KYC-lite checks",
        payment_impact="Rapid spend-up on a new identity before bust-out",
        detectable_signals=["device_new", "document_tamper_score", "mule_account_risk"],
        signal_layers={
            "rules": ["device_new", "document_tamper_score"],
            "ml": ["Amount"],
            "graph": ["mule_account_risk"],
            "intent": [],
        },
        owasp=["LLM04"],
        simulatable=True,
        keywords=["synthetic", "identity", "kyc", "onboarding", "bust-out", "credit history"],
    ),
    "authorized_push": _entry(
        name="LLM Social Engineering → Authorized Push Payment",
        category="ai_social_engineering",
        evidence="ESTABLISHED",
        feasibility="HIGH",
        tier=1,
        attack_surface="Chat or support + push payment to a new beneficiary",
        ai_component="LLM conversation that convinces the customer to send funds",
        payment_impact="Customer-authorized push to a mule",
        detectable_signals=["beneficiary_name_match", "mule_account_risk", "velocity_1h"],
        signal_layers={
            "rules": ["beneficiary_name_match", "velocity_1h"],
            "ml": ["Amount"],
            "graph": ["mule_account_risk"],
            "intent": [],
        },
        owasp=["LLM01", "LLM09"],
        simulatable=True,
        keywords=["authorized", "push", "app", "scam", "impersonat", "support", "mule"],
    ),
    "qr_swap": _entry(
        name="QR Code Swap → Payment Diversion",
        category="qr_payment",
        evidence="ESTABLISHED",
        feasibility="HIGH",
        tier=1,
        attack_surface="In-store or WhatsApp QR + UPI or wallet pay",
        ai_component="Generated lookalike merchant QR that routes funds to an attacker payee",
        payment_impact="Customer pays the attacker instead of the merchant",
        detectable_signals=["beneficiary_name_match", "location_mismatch", "mule_account_risk"],
        signal_layers={
            "rules": ["beneficiary_name_match", "location_mismatch"],
            "ml": ["Amount"],
            "graph": ["mule_account_risk"],
            "intent": [],
        },
        owasp=["LLM09"],
        simulatable=True,
        keywords=["qr", "qr code", "whatsapp", "merchant", "swap", "destination"],
    ),
    "sim_swap": _entry(
        name="SIM Swap → OTP Theft → Debit",
        category="upi_fraud",
        evidence="ESTABLISHED",
        feasibility="HIGH",
        tier=2,
        attack_surface="Mobile-number takeover + OTP + UPI or card debit",
        ai_component="Social-engineered port-out plus automated OTP harvest",
        payment_impact="Attacker-approved payments from the victim's rail",
        detectable_signals=["device_new", "location_mismatch", "velocity_1h"],
        signal_layers={
            "rules": ["device_new", "location_mismatch", "velocity_1h"],
            "ml": ["Amount"],
            "graph": [],
            "intent": [],
        },
        owasp=["LLM01"],
        simulatable=True,
        keywords=["sim", "swap", "otp", "port", "sms", "device change"],
    ),
    "refund_llm": _entry(
        name="LLM Refund Claim → Merchant Loss",
        category="refund_fraud",
        evidence="ESTABLISHED",
        feasibility="HIGH",
        tier=2,
        attack_surface="Post-purchase dispute or refund desk",
        ai_component="Generated refund narrative that matches merchant policy language",
        payment_impact="False refund or chargeback against a legitimate sale",
        detectable_signals=["velocity_1h", "Amount", "mule_account_risk"],
        signal_layers={
            "rules": ["velocity_1h"],
            "ml": ["Amount"],
            "graph": ["mule_account_risk"],
            "intent": [],
        },
        owasp=["LLM09"],
        simulatable=True,
        keywords=["refund", "chargeback", "dispute", "claim", "merchant loss"],
    ),
    "prompt_injection_pay": _entry(
        name="Prompt Injection → Agent Pays Attacker",
        category="agentic_payment",
        evidence="PLAUSIBLE",
        feasibility="HIGH",
        tier=1,
        attack_surface="Agent tool use + poisoned website or API content",
        ai_component="Indirect prompt injection that redirects an otherwise legitimate agent payment",
        payment_impact="In-scope-looking payment to an attacker-controlled payee",
        detectable_signals=["constraint_violation", "beneficiary_name_match", "amount_vs_limit_ratio"],
        signal_layers={
            "rules": ["beneficiary_name_match"],
            "ml": ["Amount"],
            "graph": ["mule_account_risk"],
            "intent": ["constraint_violation", "amount_vs_limit_ratio"],
        },
        owasp=["LLM01", "LLM06", "LLM08"],
        simulatable=True,
        keywords=["prompt injection", "indirect", "poison", "tool", "rag", "agent pay"],
    ),
    "credential_stuffing": _entry(
        name="Credential Stuffing → Account Takeover",
        category="account_takeover",
        evidence="ESTABLISHED",
        feasibility="HIGH",
        tier=2,
        attack_surface="Login velocity + reused passwords + CNP spend",
        ai_component="Optimized stuffing that stays under naive velocity rules",
        payment_impact="Taken-over account used for card-not-present fraud",
        detectable_signals=["device_new", "velocity_1h", "location_mismatch"],
        signal_layers={
            "rules": ["device_new", "velocity_1h", "location_mismatch"],
            "ml": ["Amount"],
            "graph": [],
            "intent": [],
        },
        owasp=["LLM10"],
        simulatable=True,
        keywords=["stuffing", "credential", "enumeration", "login velocity", "ato", "card testing"],
    ),
    "deepfake_kyc": _entry(
        name="Deepfake KYC Bypass → New Account",
        category="ai_identity_fraud",
        evidence="ESTABLISHED",
        feasibility="MEDIUM",
        tier=2,
        attack_surface="Remote onboarding + injected liveness video",
        ai_component="Generated face or replayed liveness that passes point-in-time KYC",
        payment_impact="New account opened for later mule spend",
        detectable_signals=["kyc_liveness_risk", "biometric_mismatch", "device_new", "mule_account_risk"],
        signal_layers={
            "rules": ["kyc_liveness_risk", "device_new"],
            "ml": ["Amount"],
            "graph": ["mule_account_risk"],
            "intent": [],
        },
        owasp=["LLM04"],
        simulatable=True,
        keywords=["deepfake", "kyc", "liveness", "onboarding", "face", "biometric"],
    ),
    "document_forgery": _entry(
        name="Document Forgery → Identity Verification",
        category="ai_identity_fraud",
        evidence="ESTABLISHED",
        feasibility="HIGH",
        tier=2,
        attack_surface="Identity verification + first CNP spend",
        ai_component="Generated ID or passport packet scored as a tamper signal, not as an image",
        payment_impact="New instrument funded after a forged KYC pack",
        detectable_signals=["document_tamper_score", "device_new", "mule_account_risk"],
        signal_layers={
            "rules": ["document_tamper_score", "device_new"],
            "ml": ["Amount"],
            "graph": ["mule_account_risk"],
            "intent": [],
        },
        owasp=["LLM09"],
        simulatable=True,
        keywords=["document", "forgery", "passport", "license", "fake id", "kyc pack"],
    ),
    "face_swap": _entry(
        name="Face Swap → Video KYC",
        category="ai_identity_fraud",
        evidence="ESTABLISHED",
        feasibility="MEDIUM",
        tier=2,
        attack_surface="Video verification + early spend",
        ai_component="Real-time face swap hypothesized at KYC; detector sees biometric mismatch on the first payments",
        payment_impact="Account opened under a swapped face, then bust-out spend",
        detectable_signals=["biometric_mismatch", "kyc_liveness_risk", "device_new"],
        signal_layers={
            "rules": ["biometric_mismatch", "kyc_liveness_risk"],
            "ml": ["Amount"],
            "graph": ["mule_account_risk"],
            "intent": [],
        },
        owasp=["LLM04"],
        simulatable=True,
        keywords=["face", "swap", "video kyc", "deepfake", "liveness"],
    ),
    "voice_clone_auth": _entry(
        name="Voice Cloning → Voice Biometric Login",
        category="authorization_fraud",
        evidence="EMERGING",
        feasibility="MEDIUM",
        tier=2,
        attack_surface="Voice authentication then card-not-present spend",
        ai_component="TTS clone hypothesized at login; overlay is a voiceprint mismatch plus session spend",
        payment_impact="Authenticated session used for unauthorized purchases",
        detectable_signals=["voiceprint_mismatch", "device_new", "velocity_1h"],
        signal_layers={
            "rules": ["voiceprint_mismatch", "velocity_1h"],
            "ml": ["Amount"],
            "graph": [],
            "intent": [],
        },
        owasp=["LLM09"],
        simulatable=True,
        keywords=["voice", "clone", "biometric", "authentication", "tts", "voiceprint"],
    ),
    "voice_impersonation": _entry(
        name="Voice Cloning Impersonation → Payment Authorization",
        category="ai_social_engineering",
        evidence="ESTABLISHED",
        feasibility="MEDIUM",
        tier=1,
        attack_surface="Phone authentication + push or collect payment",
        ai_component="Family or executive voice clone that coaches an authorized debit to a mule",
        payment_impact="Victim-authorized payment to a new beneficiary",
        detectable_signals=["voiceprint_mismatch", "beneficiary_name_match", "mule_account_risk"],
        signal_layers={
            "rules": ["voiceprint_mismatch", "beneficiary_name_match"],
            "ml": ["Amount"],
            "graph": ["mule_account_risk"],
            "intent": [],
        },
        owasp=["LLM09"],
        simulatable=True,
        keywords=["voice", "impersonat", "executive", "family", "phone", "authorize payment"],
    ),
    "deepfake_video": _entry(
        name="Deepfake Video Call → Support Impersonation",
        category="ai_identity_fraud",
        evidence="EMERGING",
        feasibility="LOW",
        tier=3,
        attack_surface="Video verification or support call, then a redirected payment",
        ai_component="Real-time deepfake video hypothesized at support; weak tabular stand-in only",
        payment_impact="Customer-authorized debit after a fake support session",
        detectable_signals=["biometric_mismatch", "beneficiary_name_match", "mule_account_risk"],
        signal_layers={
            "rules": ["biometric_mismatch"],
            "ml": ["Amount"],
            "graph": ["mule_account_risk"],
            "intent": [],
        },
        owasp=["LLM09"],
        simulatable=True,
        keywords=["deepfake", "video", "call", "support", "impersonat", "customer care"],
    ),
    "multilingual_scam": _entry(
        name="Multilingual Scam Automation → Cross-Border APP",
        category="ai_social_engineering",
        evidence="ESTABLISHED",
        feasibility="HIGH",
        tier=2,
        attack_surface="Localized lure + authorized push across corridors",
        ai_component="LLM localization of a scam narrative; overlay is cross-border mule spend, not the lure text",
        payment_impact="Victim-authorized transfer to a foreign mule",
        detectable_signals=["location_mismatch", "beneficiary_name_match", "mule_account_risk"],
        signal_layers={
            "rules": ["location_mismatch", "beneficiary_name_match"],
            "ml": ["Amount"],
            "graph": ["mule_account_risk"],
            "intent": [],
        },
        owasp=["LLM01", "LLM09"],
        simulatable=True,
        keywords=["multilingual", "localize", "translate", "cross-border", "scam automation", "global"],
    ),
    "intent_mismatch": _entry(
        name="Intent Mismatch → Agent Exceeds Delegation",
        category="authorization_fraud",
        evidence="EMERGING",
        feasibility="HIGH",
        tier=1,
        attack_surface="Signed intent vs executed payment parameters",
        ai_component="Agent executes amount or merchant outside delegated constraints",
        payment_impact="In-policy looking payment that violates the human's intent",
        detectable_signals=["constraint_violation", "amount_vs_limit_ratio"],
        signal_layers={"rules": [], "ml": ["Amount"], "graph": [], "intent": ["constraint_violation"]},
        owasp=["LLM06"],
        simulatable=False,
        keywords=["intent", "mismatch", "delegat", "constraint", "agent pay"],
    ),
    "excessive_agent": _entry(
        name="Excessive Agent Permissions",
        category="agentic_payment",
        evidence="EMERGING",
        feasibility="HIGH",
        tier=1,
        attack_surface="Over-broad agent authorization scope",
        ai_component="Agent granted wider pay rights than the user intended",
        payment_impact="Payments that look authorized because the scope was too wide",
        detectable_signals=["constraint_violation", "amount_vs_limit_ratio", "velocity_1h"],
        signal_layers={"rules": ["velocity_1h"], "ml": [], "graph": [], "intent": ["constraint_violation"]},
        owasp=["LLM06"],
        simulatable=False,
        keywords=["excessive", "agency", "permission", "scope", "agent"],
    ),
    "spoofed_agent": _entry(
        name="Spoofed Agent Identity",
        category="agentic_payment",
        evidence="PLAUSIBLE",
        feasibility="MEDIUM",
        tier=2,
        attack_surface="Agent identity / registration check at pay time",
        ai_component="Unregistered or impersonated agent presents as a trusted shopper",
        payment_impact="Payment attributed to a fake agent identity",
        detectable_signals=["device_new", "constraint_violation"],
        signal_layers={"rules": ["device_new"], "ml": [], "graph": [], "intent": ["constraint_violation"]},
        owasp=["LLM06"],
        simulatable=False,
        keywords=["spoof", "agent identity", "impersonat", "registration"],
    ),
    "velocity_burst": _entry(
        name="Velocity Attack → Limit Testing",
        category="transaction_execution",
        evidence="ESTABLISHED",
        feasibility="HIGH",
        tier=1,
        attack_surface="High-frequency authorizations against a card or UPI limit",
        ai_component="Automated burst that stays just under naive velocity rules",
        payment_impact="Many small or stepped-up payments in a short window",
        detectable_signals=["velocity_1h", "Amount"],
        signal_layers={"rules": ["velocity_1h"], "ml": ["Amount"], "graph": [], "intent": []},
        owasp=["LLM10"],
        simulatable=False,
        keywords=["velocity", "burst", "testing", "limit", "frequency"],
    ),
    "screen_share_otp": _entry(
        name="Screen-Share OTP Theft",
        category="upi_fraud",
        evidence="ESTABLISHED",
        feasibility="MEDIUM",
        tier=2,
        attack_surface="Remote-assist session + OTP on device",
        ai_component="Social script that gets the user to share the screen during OTP",
        payment_impact="Attacker-approved debit after OTP capture",
        detectable_signals=["device_new", "velocity_1h", "beneficiary_name_match"],
        signal_layers={"rules": ["device_new", "beneficiary_name_match"], "ml": [], "graph": [], "intent": []},
        owasp=["LLM01"],
        simulatable=False,
        keywords=["screen", "share", "otp", "remote assist", "upi"],
    ),
    "fake_customer_care": _entry(
        name="Fake Customer Care Link",
        category="ai_social_engineering",
        evidence="ESTABLISHED",
        feasibility="HIGH",
        tier=2,
        attack_surface="Support impersonation + payment or credential harvest",
        ai_component="LLM chat that mimics bank support and redirects funds or sessions",
        payment_impact="Customer-authorized debit or session handoff to an attacker",
        detectable_signals=["beneficiary_name_match", "mule_account_risk", "velocity_1h"],
        signal_layers={"rules": ["beneficiary_name_match"], "ml": [], "graph": ["mule_account_risk"], "intent": []},
        owasp=["LLM01", "LLM09"],
        simulatable=False,
        keywords=["customer care", "support", "impersonat", "helpdesk", "link"],
    ),
    "cnp_testing": _entry(
        name="Card Testing Automation",
        category="card_payment",
        evidence="ESTABLISHED",
        feasibility="HIGH",
        tier=2,
        attack_surface="Low-value CNP authorizations to validate stolen PANs",
        ai_component="ML-prioritized BIN and amount testing under velocity caps",
        payment_impact="Many small approvals then a high-value cash-out",
        detectable_signals=["velocity_1h", "Amount", "device_new"],
        signal_layers={"rules": ["velocity_1h", "device_new"], "ml": ["Amount"], "graph": [], "intent": []},
        owasp=["LLM10"],
        simulatable=False,
        keywords=["card testing", "cnp", "bin", "enumeration", "auth"],
    ),
    "payment_link_swap": _entry(
        name="Payment Link Manipulation",
        category="payment_link",
        evidence="ESTABLISHED",
        feasibility="HIGH",
        tier=2,
        attack_surface="Shared payment link or invoice URL",
        ai_component="Generated lookalike link that changes the payee",
        payment_impact="Customer pays an attacker-controlled destination",
        detectable_signals=["beneficiary_name_match", "mule_account_risk", "location_mismatch"],
        signal_layers={"rules": ["beneficiary_name_match"], "ml": [], "graph": ["mule_account_risk"], "intent": []},
        owasp=["LLM09"],
        simulatable=False,
        keywords=["payment link", "invoice", "url", "destination", "swap"],
    ),
    "invoice_fraud": _entry(
        name="AI-Generated Invoice Fraud",
        category="merchant_interaction",
        evidence="ESTABLISHED",
        feasibility="HIGH",
        tier=2,
        attack_surface="AP inbox + generated invoice",
        ai_component="LLM invoice that matches vendor format with a swapped account",
        payment_impact="Treasury pays the attacker instead of the vendor",
        detectable_signals=["beneficiary_name_match", "mule_account_risk", "Amount"],
        signal_layers={"rules": ["beneficiary_name_match"], "ml": ["Amount"], "graph": ["mule_account_risk"], "intent": []},
        owasp=["LLM09"],
        simulatable=False,
        keywords=["invoice", "vendor", "ap", "b2b", "account swap"],
    ),
    "wallet_ato": _entry(
        name="Digital Wallet Account Takeover",
        category="digital_wallet",
        evidence="ESTABLISHED",
        feasibility="HIGH",
        tier=2,
        attack_surface="Wallet login + stored funding instrument",
        ai_component="Credential or session theft optimized for wallet rails",
        payment_impact="P2P or merchant pay from the taken-over wallet",
        detectable_signals=["device_new", "location_mismatch", "velocity_1h"],
        signal_layers={"rules": ["device_new", "velocity_1h"], "ml": [], "graph": [], "intent": []},
        owasp=["LLM01"],
        simulatable=False,
        keywords=["wallet", "ato", "p2p", "stored card"],
    ),
    "wallet_transfer": _entry(
        name="Wallet-to-Wallet Layering",
        category="digital_wallet",
        evidence="ESTABLISHED",
        feasibility="MEDIUM",
        tier=2,
        attack_surface="Rapid wallet hops after an inbound debit",
        ai_component="Automated layering across mule wallets",
        payment_impact="Proceeds leave the first-hop account before freeze",
        detectable_signals=["velocity_1h", "mule_account_risk", "beneficiary_name_match"],
        signal_layers={"rules": ["velocity_1h"], "ml": [], "graph": ["mule_account_risk"], "intent": []},
        owasp=["LLM10"],
        simulatable=False,
        keywords=["wallet", "layering", "mule", "p2p", "hop"],
    ),
    "mule_network": _entry(
        name="Mule Account Network",
        category="coordinated_networks",
        evidence="ESTABLISHED",
        feasibility="MEDIUM",
        tier=2,
        attack_surface="Shared payee / device / IP graph",
        ai_component="Coordinated accounts that look independent row-by-row",
        payment_impact="Many small credits into a mule cluster",
        detectable_signals=["mule_account_risk", "beneficiary_name_match", "velocity_1h"],
        signal_layers={"rules": [], "ml": [], "graph": ["mule_account_risk"], "intent": []},
        owasp=["LLM10"],
        simulatable=False,
        keywords=["mule", "network", "ring", "cluster", "graph"],
    ),
    "chargeback_abuse": _entry(
        name="Chargeback Abuse",
        category="chargeback_fraud",
        evidence="ESTABLISHED",
        feasibility="HIGH",
        tier=3,
        attack_surface="Dispute desk after a completed sale",
        ai_component="Generated dispute letters that match issuer policy language",
        payment_impact="Merchant loss after goods or services were delivered",
        detectable_signals=["velocity_1h", "Amount", "mule_account_risk"],
        signal_layers={"rules": ["velocity_1h"], "ml": ["Amount"], "graph": [], "intent": []},
        owasp=["LLM09"],
        simulatable=False,
        keywords=["chargeback", "friendly fraud", "dispute", "issuer"],
    ),
    "destination_substitution": _entry(
        name="Payment Destination Substitution",
        category="transaction_execution",
        evidence="PLAUSIBLE",
        feasibility="HIGH",
        tier=2,
        attack_surface="Payee field swapped after a legitimate instruction",
        ai_component="Tool or page injection that changes destination only",
        payment_impact="Correct amount to the wrong beneficiary",
        detectable_signals=["beneficiary_name_match", "mule_account_risk", "constraint_violation"],
        signal_layers={
            "rules": ["beneficiary_name_match"],
            "ml": ["Amount"],
            "graph": ["mule_account_risk"],
            "intent": ["constraint_violation"],
        },
        owasp=["LLM01", "LLM08"],
        simulatable=False,
        keywords=["destination", "substitution", "payee", "beneficiary", "swap"],
    ),
    "session_hijack": _entry(
        name="Session Hijack After Login",
        category="account_takeover",
        evidence="EMERGING",
        feasibility="MEDIUM",
        tier=2,
        attack_surface="Authenticated session token reused on a second device",
        ai_component="Generated session-replay traffic that looks like the real user",
        payment_impact="Spend from a live session without a new login event",
        detectable_signals=["device_new", "location_mismatch", "velocity_1h"],
        signal_layers={
            "rules": ["device_new", "location_mismatch"],
            "ml": ["velocity_1h"],
            "graph": [],
            "intent": [],
        },
        owasp=["LLM10"],
        simulatable=False,
        keywords=["session", "hijack", "cookie", "token", "replay"],
    ),
    "adversarial_row": _entry(
        name="Adversarial Feature Perturbation",
        category="adaptive_fraud",
        evidence="PLAUSIBLE",
        feasibility="HIGH",
        tier=2,
        attack_surface="Tabular features nudged after a rule mutation",
        ai_component="Search that keeps overlay flags while shrinking detector score",
        payment_impact="Same family story, lower score — closed-loop novelty, not a new overlay",
        detectable_signals=["Amount", "mule_account_risk", "velocity_1h"],
        signal_layers={
            "rules": ["velocity_1h"],
            "ml": ["Amount"],
            "graph": ["mule_account_risk"],
            "intent": [],
        },
        owasp=["LLM04"],
        simulatable=False,
        keywords=["adversarial", "perturbation", "evasive", "washed", "optimizer"],
    ),
    "agent_to_agent": _entry(
        name="Agent-to-Agent Payment Collusion",
        category="agentic_payment",
        evidence="PLAUSIBLE",
        feasibility="MEDIUM",
        tier=2,
        attack_surface="Two delegated agents settling a payee the user never named",
        ai_component="Tool-to-tool instruction that bypasses a human confirmation step",
        payment_impact="Transfer that satisfies each agent policy but not the user intent",
        detectable_signals=["constraint_violation", "beneficiary_name_match", "amount_vs_limit_ratio"],
        signal_layers={
            "rules": ["beneficiary_name_match"],
            "ml": ["Amount"],
            "graph": [],
            "intent": ["constraint_violation", "amount_vs_limit_ratio"],
        },
        owasp=["LLM01", "LLM06"],
        simulatable=False,
        keywords=["agent", "collusion", "delegation", "tool", "a2a"],
    ),
    "fake_merchant": _entry(
        name="Fake Merchant Onboarding",
        category="merchant_interaction",
        evidence="ESTABLISHED",
        feasibility="MEDIUM",
        tier=3,
        attack_surface="Acquirer onboarding with generated storefront and KYC pack",
        ai_component="Synthetic business documents used to stand up a cash-out merchant",
        payment_impact="Card or wallet credits into a mule merchant before shutdown",
        detectable_signals=["mule_account_risk", "velocity_1h", "device_new"],
        signal_layers={
            "rules": ["velocity_1h", "device_new"],
            "ml": ["Amount"],
            "graph": ["mule_account_risk"],
            "intent": [],
        },
        owasp=["LLM09"],
        simulatable=False,
        keywords=["merchant", "onboarding", "storefront", "acquirer", "mule"],
    ),
}

FAMILY_LABELS = {fid: meta["name"] for fid, meta in ATTACK_CATALOG.items()}
DISCOVERY_FAMILIES = list(ATTACK_CATALOG.keys())
SIMULATABLE_FAMILIES = [fid for fid, meta in ATTACK_CATALOG.items() if meta["simulatable"]]


def catalog_status(family: str) -> str:
    meta = ATTACK_CATALOG.get(family)
    if meta and meta["simulatable"]:
        return "simulatable"
    return "identified_only"


def hypothesis_from_catalog(
    family: str,
    *,
    confidence: float,
    source_ids: list[str],
    index: int,
) -> dict[str, Any]:
    meta = ATTACK_CATALOG[family]
    return {
        "hypothesis_id": f"HYP-{index:03d}",
        "attack_name": meta["name"],
        "attack_family": family,
        "category": meta.get("category"),
        "evidence": meta.get("evidence"),
        "feasibility": meta.get("feasibility"),
        "tier": meta.get("tier"),
        "attack_surface": meta["attack_surface"],
        "ai_component": meta["ai_component"],
        "payment_impact": meta["payment_impact"],
        "detectable_signals": list(meta["detectable_signals"]),
        "signal_layers": dict(meta.get("signal_layers") or {}),
        "owasp_mapping": list(meta["owasp"]),
        "confidence_score": round(float(confidence), 3),
        "catalog_status": catalog_status(family),
        "source_ids": source_ids,
    }


def diversity_metrics(hypotheses: list[dict[str, Any]]) -> dict[str, Any]:
    families = []
    seen = set()
    for row in hypotheses:
        fid = row.get("attack_family")
        if fid and fid not in seen:
            seen.add(fid)
            families.append(fid)
    simulatable = sum(1 for fid in families if catalog_status(fid) == "simulatable")
    identified = len(families) - simulatable
    catalog_size = len(ATTACK_CATALOG)
    categories = {
        ATTACK_CATALOG[fid]["category"]
        for fid in families
        if fid in ATTACK_CATALOG and ATTACK_CATALOG[fid].get("category")
    }
    evidence_mix: dict[str, int] = {}
    for fid in families:
        ev = (ATTACK_CATALOG.get(fid) or {}).get("evidence") or "UNKNOWN"
        evidence_mix[ev] = evidence_mix.get(ev, 0) + 1
    tier1 = sum(1 for fid in families if (ATTACK_CATALOG.get(fid) or {}).get("tier") == 1)
    return {
        "n_hypotheses": len(hypotheses),
        "n_distinct_families": len(families),
        "catalog_size": catalog_size,
        "simulatable_count": simulatable,
        "identified_only_count": identified,
        "coverage": round(len(families) / catalog_size, 3) if catalog_size else 0.0,
        "category_coverage": round(len(categories) / max(len(TAXONOMY), 1), 3),
        "n_categories": len(categories),
        "n_taxonomy": len(TAXONOMY),
        "tier1_count": tier1,
        "evidence_mix": evidence_mix,
        "vs_target": DIVERSITY_TARGET,
        "families": families,
    }


__all__ = [
    "ATTACK_CATALOG",
    "CORE_ATTACK_VECTORS",
    "CORE_FAMILY_IDS",
    "IDENTITY_AUTH_FAMILY_IDS",
    "DISCOVERY_FAMILIES",
    "DIVERSITY_TARGET",
    "FAMILY_LABELS",
    "SIMULATABLE_FAMILIES",
    "TAXONOMY",
    "VECTOR_TO_FAMILY",
    "catalog_status",
    "diversity_metrics",
    "hypothesis_from_catalog",
]
