[theme]
base = "light"
primaryColor = "#EB001B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#111111"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
headless = true
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
